apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tashi-deploy-pet-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tashi-179/pet-argocd-k8s.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: pet

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
