apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tashi-deploy-pet
  name: tashi-deploy-pet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tashi-deploy-pet
  template:
    metadata:
      labels:
        app: tashi-deploy-pet
    spec:
      containers:
      - image: tashi179/tashi-deploy-pet:19
        name: tashi-deploy-pet
