apiVersion: v1
kind: Service
metadata:
  labels:
    app: tashi-deploy-pet-svc
  name: tashi-deploy-pet-svc
  #namespace: pet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tashi-deploy-pet
  type: NodePort
